# Use the official OpenJDK 16 image as the base image
FROM openjdk:16-jdk-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the compiled JAR file into the container at /app
COPY target/bookstore-0.0.1-SNAPSHOT.jar app.jar

# Expose the port that your Spring Boot app listens on
EXPOSE 8080

# Define the command to run your application when the container starts
CMD ["java", "-jar", "app.jar"]
